Traceback (most recent call last):
  File "d:\Drive\Code\ATBSWP\test.py", line 3, in <module>
    raise Exception('This is the error message.')
Exception: This is the error message.
